INSERT INTO TASK(ID,NAME,AGE,ADDRESS,PROFESSION) VALUES(100,'MURALI',19,'CHENNAI','STUDENT');
INSERT INTO TASK(ID,NAME,AGE,ADDRESS,PROFESSION) VALUES(200,'GURU',19,'SALEM','STUDENT');
INSERT INTO TASK(ID,NAME,AGE,ADDRESS,PROFESSION) VALUES(300,'SURYA',19,'SALEM','STUDENT');
INSERT INTO TASK(ID,NAME,AGE,ADDRESS,PROFESSION) VALUES(400,'MADHAVAN',19,'CHENNAI','STUDENT');